#!/usr/bin/env python3

import argparse
import json
import logging
import sys
from squad_client.core.api import SquadApi
from squad_client.core.models import Squad, SquadObjectJSONEncoder, TestRun
from squad_client.utils import first, getid

SquadApi.configure(cache=3600, url="https://qa-reports.linaro.org/")

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


def arg_parser():
    parser = argparse.ArgumentParser(description="List data about a test")

    parser.add_argument(
        "--group",
        required=True,
        help="squad group",
    )

    parser.add_argument(
        "--project",
        required=True,
        help="squad project",
    )

    parser.add_argument(
        "--build",
        required=True,
        help="squad build",
    )

    parser.add_argument(
        "--environment",
        required=True,
        help="squad environment",
    )

    parser.add_argument(
        "--suite",
        required=True,
        help="squad suite",
    )

    parser.add_argument(
        "--test",
        required=True,
        help="squad test",
    )

    return parser


def run():
    args = arg_parser().parse_args()

    group = Squad().group(args.group)
    if group is None:
        logger.error(f"Get group failed. Group not found: '{args.group}'.")
        return -1

    project = group.project(args.project)
    if project is None:
        logger.error(f"Get project failed. Project not found: '{args.project}'.")
        return -1

    build = project.build(args.build)
    if build is None:
        logger.error(f"Get build failed. Build not found: '{args.build}'.")
        return -1

    environment = project.environment(args.environment)
    if environment is None:
        logger.error(f"Get environment failed. Environment not found: '{args.environment}'.")
        return -1

    suite = project.suite(args.suite)
    if suite is None:
        logger.error(f"Get suite failed. Suite not found: '{args.suite}'.")
        return -1

    test = first(Squad().tests(
        build=build.id,
        environment=environment.id,
        suite=suite.id,
        metadata__name=args.test,
        count=1,
    ))

    if not test:
        logger.error(f"Get test failed. Test not found: '{args.test}'.")
        return -1

    test_run = TestRun(getid(test.test_run))

    flat = test.__dict__

    flat.update({
        "group": group.slug,
        "project": project.slug,
        "environment": environment.slug,
        "suite": suite.slug,
        "build": build.version,
        "metadata": test_run.metadata,
    })

    flat.pop("test_run")

    print(json.dumps(flat, indent=2, cls=SquadObjectJSONEncoder))


if __name__ == "__main__":
    sys.exit(run())
